before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  -
    id: kubectl-credentials-broker
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
    goarch:
      - amd64
    binary: kubectl-credentials_broker
    ldflags:
      - -w -s -X github.com/takumakume/kubectl-credentials-broker/cmd.Version={{.Version}}
  -
    id: kubectl-credentials-broker-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: kubectl-credentials_broker
    ldflags:
      - -w -s -X github.com/takumakume/kubectl-credentials-broker/cmd.Version={{.Version}}
nfpms:
  -
    id: kubectl-credentials-broker-nfpms
    builds:
    - kubectl-credentials-broker-linux
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    homepage: https://github.com/takumakume/kubectl-credentials-broker
    maintainer: Takuma Kume <takuma.kume@gmail.com>
    description: This tool is a kubectl plugin that supports updating credentials with kube-apiserver
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    epoch: 1
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
brews:
  - name: kubectl-credentials-broker
    tap:
      owner: takumakume
      name: homebrew-tap
    commit_author:
      name: takumakume
      email: takuma.kume@gmail.com
    homepage: https://github.com/takumakume/kubectl-credentials-broker
    description: Before kubectl run execute any command provides credential to kubectl
    install: |
      bin.install "kubectl-credentials_broker"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
