before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: kubectl-credentials_broker
    ldflags:
      - -w -s -X github.com/takumakume/kubectl-credentials-broker/cmd.Version={{.Version}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - name: kubectl-credentials-broker
    tap:
      owner: takumakume
      name: homebrew-tap
    commit_author:
      name: takumakume
      email: takuma.kume@gmail.com
    homepage: https://github.com/takumakume/kubectl-credentials-broker
    description: Before kubectl run execute any command provides credential to kubectl
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
